### ISSUE TITLE
Prosba

### ISSUE THREAD

**Issue by oretlogin** [Raiper34/plugin.video.mojetv-archiv#1]
Zdravím, bylo by možné získat přístup (login, heslo) do vašeho addonu. Velice by mne zajímalo jak jste to pojal. Stačilo by třeba jen na jeden den pokud je skupina uzavřená. Předem díky. Hospodarsky

**Comment by Raiper34** [comment]
Zdravim, 
potrebujete meno a heslo k mojetv, nie k addonu, addon iba bere informacie z ich webu ;) 
Ponate je to tak ze zvolite si televizu, potom na druhej stranke datum a nakoniec konkretny zaznam.
